# Generated by Django 2.1.7 on 2019-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOne', models.CharField(max_length=20)),
                ('fieldTwo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('permissions', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='TAsInCourse',
            field=models.ManyToManyField(blank=True, related_name='TAs', to='Final.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, related_name='students', to='Final.User'),
        ),
    ]
