# Generated by Django 2.2 on 2019-04-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOne', models.CharField(max_length=20)),
                ('fieldTwo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('permissions', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAassignedToLab', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('studentsInLab', models.ManyToManyField(blank=True, related_name='studentsInThisRelNameLab', to='Final.User')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('LabSections', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Final.Lab')),
                ('TAsInCourse', models.ManyToManyField(blank=True, related_name='TAs', to='Final.User')),
                ('studentsInCourse', models.ManyToManyField(blank=True, related_name='students', to='Final.User')),
            ],
        ),
    ]
