# Generated by Django 2.2 on 2019-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('permissions', models.CharField(max_length=20)),
                ('pa', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
