# Generated by Django 2.2 on 2019-04-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='LabSections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Final.Lab'),
        ),
    ]
