# Generated by Django 2.2 on 2019-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_auto_20190418_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studentsInCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, null=True, to='Final.User'),
        ),
    ]
