# Generated by Django 2.2 on 2019-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
