# Generated by Django 2.2 on 2019-04-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_auto_20190430_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='LabSections',
        ),
        migrations.AddField(
            model_name='lab',
            name='ParentCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Final.Course'),
        ),
    ]
