# Generated by Django 2.2 on 2019-05-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0003_auto_20190430_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='TAassignedToLab',
            new_name='TA',
        ),
    ]
