# Generated by Django 2.2 on 2019-04-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0003_auto_20190418_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, to='Final.User'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsInCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final.Course')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final.User')),
            ],
        ),
    ]
