# Generated by Django 2.2 on 2019-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0004_auto_20190502_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='labNumber',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
