# Generated by Django 2.2 on 2019-05-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0005_lab_labnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
