# Generated by Django 2.2 on 2019-04-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0005_auto_20190422_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myCourses',
        ),
        migrations.AddField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, to='Final.User'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
