# Generated by Django 2.2 on 2019-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0006_auto_20190422_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TAsInCourse',
            field=models.ManyToManyField(blank=True, related_name='TAs', to='Final.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, related_name='students', to='Final.User'),
        ),
    ]
